services:
    postgres:
        image: postgres:latest
        container_name: sakila-db
        restart: always
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DATABASE}
        logging: # option de paramétrage des logs
          options:
            max-size: 10m # fichier de 10 Mo maximum
            max-file: "3" # jusqu'à 3 fichiers de log
        ports:
          - '5532:5432' # redirection de port, le nombre de gauche correspond au port local et le nombre de droite au utilisé sur le conteneur
        volumes:
          # on monte le volume pointant vers le dossier contenant les informations des BDD 
          - ${POSTGRES_DUMP_DIR}:/var/lib/postgresql/data
          # Afin de sauvergarder les données dans le dépôt git, il faut enlever la ligne "postgres-data" du .gitignore
          
          # on monte également le dossier contenant les variables d'exécution (/var/run sur Linux).
          # ce dossier contient, par exemple, un fichier ".lock" protégeant l'accès en écriture aux fichiers de BDD
          # lorsque le SGBDR est démarré 
          # - ./postgres-run:/var/run/postgresql
          # copie du script SQL de création de base de données sur le conteneur
          - ./db/dump/V1.0__sakila-schema.sql:/docker-entrypoint-initdb.d/V1.0__sakila-schema.sql
          - ./db/dump/V1.2__sakila-data.sql:/docker-entrypoint-initdb.d/V1.2__sakila-data.sql
    dbeaver:
      image: dbeaver/cloudbeaver:latest
      container_name: cloudbeaver
      ports:
        - "8081:8978"
      volumes:
        - ./cloudbeaver-data:/opt/cloudbeaver/workspace # Stocke les données localement pour persistance
      environment:
        - CB_ADMIN_NAME=${DBEAVER_NAME}
        - CL_ADMIN_PASSWORD=${DBEAVER_PASSWORD}
      restart: unless-stopped # relance automatiquement le conteneur si necessaire

